name: auth_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/auth_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
